/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.Arrays;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class UserFrame extends javax.swing.JFrame {
    Timer timer;
    int[] numbers = {0,0,0,0,0};
    int point = 0;
    
    /**
     * Creates new form index
     */
    public UserFrame() {
        initComponents();
    }
    
    public void random(){
        int min = 0;
        int max = 1000;
        int random;
        
        for (int i = 0; i < this.numbers.length; i++) {
            random = (int)Math.floor(Math.random()*(max-min+1)+min);
            this.numbers[i] = random;
        }        
    }
    
    public void clear(){
        fieldNum0.setText("");
        fieldNum1.setText("");
        fieldNum2.setText("");
        fieldNum3.setText("");
        fieldNum4.setText("");
    }
    
    public void setText(){
        random();
        labelNum0.setText(String.valueOf(this.numbers[0]));
        labelNum1.setText(String.valueOf(this.numbers[1]));
        labelNum2.setText(String.valueOf(this.numbers[2]));
        labelNum3.setText(String.valueOf(this.numbers[3]));
        labelNum4.setText(String.valueOf(this.numbers[4]));
    }
    
    //function to sort the random numbers
    //using selection sort algorithm
    public void selectionSort(int[] numbers){
        //put the array length to variabel
        int length = numbers.length;
        
        //loop the unsorted array
        for (int i = 0; i < length - 1; i++){    
            
            //find the minimum element(index) in unsorted array
            int minIndex = i;  
            for (int j = i + 1; j < length; j++){  
                if (numbers[j] < numbers[minIndex]){  
                    minIndex = j;
                }  
            } 
            
            //swap the found minimum element(index) with the first element(index)
            int temp = numbers[minIndex];   
            numbers[minIndex] = numbers[i];  
            numbers[i] = temp;  
        }  
    }
    
    class setTimer extends TimerTask {
        int second = Integer.parseInt(labelTimer.getText());
     
        public void run() {
            if (second > 0){
                labelTimer.setText(String.valueOf(second));
                second--;
            }else{
                labelTimer.setText("0");
            }
        }
    }
    
    public void timer(){
        timer = new Timer();
        timer.schedule(new setTimer(),0,1000);
    }
    
    public void startTimer(){
        labelTimer.setText("60");        
        setText();
        this.timer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        labelNum0 = new javax.swing.JLabel();
        labelNum1 = new javax.swing.JLabel();
        labelNum2 = new javax.swing.JLabel();
        labelNum3 = new javax.swing.JLabel();
        labelNum4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fieldNum0 = new javax.swing.JTextField();
        fieldNum1 = new javax.swing.JTextField();
        fieldNum2 = new javax.swing.JTextField();
        fieldNum3 = new javax.swing.JTextField();
        fieldNum4 = new javax.swing.JTextField();
        labelTimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        labelNum0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNum0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum0.setText("0");
        labelNum0.setToolTipText("");

        labelNum1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum1.setText("0");

        labelNum2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum2.setText("0");

        labelNum3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNum3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum3.setText("0");

        labelNum4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNum4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNum4.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SORT THE NUMBERS BEFORE TIME RUNS OUT !!!");

        fieldNum0.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fieldNum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fieldNum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fieldNum3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fieldNum4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        labelTimer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTimer.setForeground(java.awt.Color.red);
        labelTimer.setText("--");
        labelTimer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                labelTimerPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(labelNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelTimer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jSeparator1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fieldNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(labelTimer))
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(fieldNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.startTimer();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

      
    }//GEN-LAST:event_formWindowActivated

    private void labelTimerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_labelTimerPropertyChange
        if (labelTimer.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Time Out", "Notification", JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null, "Total Point : " + this.point, "Notification", JOptionPane.INFORMATION_MESSAGE);
            
            this.clear();
            
            int option = JOptionPane.showConfirmDialog(null, "Try Again?", "Notification", JOptionPane.YES_NO_OPTION);
            
            if(option == JOptionPane.YES_OPTION){
                this.setVisible(false);
                UserFrame user = new UserFrame();
                user.setLocationRelativeTo(null);
                user.setVisible(true);
            }else{
                System.exit(0);
            }
        }
    }//GEN-LAST:event_labelTimerPropertyChange

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String num0 = fieldNum0.getText();
        String num1 = fieldNum1.getText();
        String num2 = fieldNum2.getText();
        String num3 = fieldNum3.getText();
        String num4 = fieldNum4.getText();
     
        if(num0.isEmpty() || num1.isEmpty() || num2.isEmpty() || num3.isEmpty() || num4.isEmpty()){
            JOptionPane.showMessageDialog(null, "All Field Cannot Null", "Notification", JOptionPane.INFORMATION_MESSAGE);
            return;
        }else if(num0.equals("0") || num1.equals("0") || num2.equals("0") || num3.equals("0") || num4.equals("0")){
            JOptionPane.showMessageDialog(null, "Cannot input zero (0)", "Notification", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        int[] nums = {
            Integer.valueOf(num0),
            Integer.valueOf(num1),
            Integer.valueOf(num2),
            Integer.valueOf(num3),
            Integer.valueOf(num4),
        };
         
        //call the sort function with parameter random numbers
        this.selectionSort(this.numbers);
        
        //check if sorted numbers from user is equal to sorted numbers from sort function
        //using Arrays.equals() function
        
        //if true will display correct message and point +5
        //if false will display wrong message and clear the textfield
        if(!Arrays.equals(nums, this.numbers)){
            JOptionPane.showMessageDialog(null, "Wrong! Try Again");
            this.clear();
            return;
        }
        
        JOptionPane.showMessageDialog(null, "Correct!");
        this.point += 5;
        
        for (int i = 0; i < this.numbers.length; i++) {
            this.numbers[i] = 0;
        }
        
        clear();
        random();
        setText();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JTextField fieldNum0;
    private javax.swing.JTextField fieldNum1;
    private javax.swing.JTextField fieldNum2;
    private javax.swing.JTextField fieldNum3;
    private javax.swing.JTextField fieldNum4;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelNum0;
    private javax.swing.JLabel labelNum1;
    private javax.swing.JLabel labelNum2;
    private javax.swing.JLabel labelNum3;
    private javax.swing.JLabel labelNum4;
    private javax.swing.JLabel labelTimer;
    // End of variables declaration//GEN-END:variables
}
